### ISSUE TITLE
Remove bundled tests

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/tomlkit-feedstock#24]
Looks like this puts the hated `tests` folder into `site-packages`, where they aren't doing anybody any good...

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: defaults/noarch::pastel-0.2.0-py_0, defaults/linux-64::tomlkit-0.7.0-py37h89c1867_2
  path: 'lib/python3.7/site-packages/tests/conftest.py'
```

Found while looking into:
- https://github.com/conda-forge/poetry-feedstock/issues/39

I'd do an upstream pr, but they're actively _asking_ for it so...

**Comment by ocefpaf** [comment]
The number of `tests` packages is too high!!!

Yes, please. Remove it.

**Comment by bollwyvl** [comment]
😂
